package com.gamebuddy.shared.mail;

import jakarta.mail.internet.MimeMessage;
import java.nio.charset.StandardCharsets;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.ClassPathResource;
import org.springframework.mail.MailException;
import org.springframework.mail.MailPreparationException;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Component;

/**
 * Sends the branded transactional emails.
 *
 * <p>Everything leaves as {@code multipart/related( multipart/alternative(text, html),
 * logo )} — the two bodies from {@link EmailRenderer}, plus the mark as an inline part the
 * HTML refers to by {@code cid:}.
 *
 * <h2>Why the logo is attached rather than linked</h2>
 *
 * <p>A hosted {@code https://…/logo.png} is the more common choice and it is the one this
 * deliberately does not make, for two reasons:
 *
 * <ul>
 *   <li><strong>Remote images are blocked by default</strong> in Outlook and in any client
 *       whose user has not marked the sender as safe — which is every recipient of a
 *       verification email, since it is by definition the first message they get from us.
 *       An inline part is part of the message and displays without asking.
 *   <li><strong>It cannot rot.</strong> The asset ships inside the same jar as the code
 *       that references it, so there is no window where the backend is deployed and the
 *       image is not, and no email sitting in an inbox pointing at a path a later website
 *       redeploy has moved.
 * </ul>
 *
 * <p>The cost is a small attachment on every message and a paperclip icon in a few clients.
 * Five kilobytes for a logo that always renders is the right side of that trade.
 *
 * <h2>Failure</h2>
 *
 * <p>{@link MailException} propagates, which is what every caller here is written around:
 * the verification paths let it roll their transaction back rather than leave an account
 * holding an address nobody can prove they own, and the one caller for which the damage is
 * already done — the password-changed notice — catches it deliberately.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class Mailer {

    /** Where the mark lives in the jar. Regenerated by GameBuddy-Web/scripts/generate-email-logo.mjs. */
    private static final String LOGO_RESOURCE = "email/logo.png";

    private final JavaMailSender mailSender;

    @Value("${gamebuddy.mail.from:noreply@mail.findgamebuddy.com}")
    private String from;

    /**
     * The display name on the From header.
     *
     * <p>Worth setting: without it the inbox shows the bare address, and "noreply@mail…" as
     * a sender name is the single strongest visual cue that a message is machine-generated
     * junk. With it, the row reads "GameBuddy".
     */
    @Value("${gamebuddy.mail.from-name:GameBuddy}")
    private String fromName;

    /** Builds and sends one message. Throws {@link MailException} if it cannot go. */
    public void send(String to, EmailContent content) {
        MimeMessage message = mailSender.createMimeMessage();
        try {
            // true: multipart. The charset is explicit because the default depends on the
            // platform, and a message that renders in Docker and mangles an apostrophe on
            // Windows is a bug nobody finds until it is in front of a user.
            MimeMessageHelper helper = new MimeMessageHelper(message, true, StandardCharsets.UTF_8.name());
            helper.setFrom(from, fromName);
            helper.setTo(to);
            helper.setSubject(content.subject());
            // Plain first, HTML second — that is the order multipart/alternative requires,
            // and this two-argument form writes it correctly. Clients display the last part
            // they understand, so a text-only client stops at the first and the rest get
            // the second.
            helper.setText(EmailRenderer.toPlainText(content), EmailRenderer.toHtml(content));

            ClassPathResource logo = new ClassPathResource(LOGO_RESOURCE);
            if (logo.exists()) {
                helper.addInline(EmailRenderer.LOGO_CID, logo, "image/png");
            } else {
                // Not fatal. A missing asset should cost the reader a logo, not their
                // verification code — the alt text carries the name either way.
                log.warn("{} is missing from the classpath; sending without the mark", LOGO_RESOURCE);
            }
        } catch (MailException e) {
            throw e;
        } catch (Exception e) {
            // MessagingException and UnsupportedEncodingException are checked and mean the
            // message could not be assembled at all. Callers are written against Spring's
            // unchecked mail hierarchy, so it becomes part of it rather than a second kind
            // of failure every call site has to know about.
            throw new MailPreparationException("Could not build the '" + content.subject() + "' email", e);
        }

        mailSender.send(message);
    }
}
