import { useQuery } from '@tanstack/react-query';
import { useRouter, type Href } from 'expo-router';
import { memo, useCallback } from 'react';
import { FlatList, Pressable, View } from 'react-native';
import { adminApi } from '../../src/api/admin';
import type { CaseSummary } from '../../src/api/types';
import { Card, ErrorNotice, Screen, Text } from '../../src/ui';

/**
 * The moderation queue — one row per reported person, not per report.
 *
 * A case gathers every open report against an account, so the decision a moderator makes
 * is about the person, once, rather than the same account arriving five times. Urgent
 * cases (an underage report, or enough distinct people that the profile was auto-hidden)
 * sort to the top; within a status, oldest first, because the terms promise a decision
 * within 24 hours and the oldest is the one closest to breaking it.
 *
 * The row is a summary; opening it is the audited act, because reading a reported
 * conversation means decrypting it. So the list shows who and how many, and the evidence
 * is one tap away on the case screen.
 */
export default function ReportsScreen() {
  const router = useRouter();

  const cases = useQuery({
    queryKey: ['admin', 'cases'],
    queryFn: () => adminApi.cases(),
    staleTime: 30_000,
  });

  const open = cases.data?.cases ?? [];
  const keyExtractor = useCallback((c: CaseSummary) => c.caseId, []);
  // Cast because the generated route table is regenerated by the bundler, not by tsc; the
  // `case` route file exists, so this resolves at build time.
  const onOpen = useCallback((caseId: string) => router.push(`/case?id=${caseId}` as Href), [router]);
  const renderRow = useCallback(
    ({ item }: { item: CaseSummary }) => <CaseRow item={item} onOpen={onOpen} />,
    [onOpen],
  );

  return (
    <Screen edges={['top']}>
      <View className="pb-3 pt-2">
        <Text variant="overline">Moderation</Text>
        <Text variant="title">Cases</Text>
      </View>

      {cases.error && <ErrorNotice error={cases.error} onRetry={() => void cases.refetch()} />}

      <FlatList
        data={open}
        keyExtractor={keyExtractor}
        showsVerticalScrollIndicator={false}
        contentContainerClassName="pb-8"
        onRefresh={() => void cases.refetch()}
        refreshing={cases.isFetching}
        ListEmptyComponent={
          cases.isLoading ? null : (
            <Text variant="body" className="mt-8 text-center text-muted">
              Nothing waiting. Reported people land here as cases.
            </Text>
          )
        }
        renderItem={renderRow}
      />
    </Screen>
  );
}

/** "3h ago", precise enough that more would not change a decision. */
function when(iso: string) {
  const minutes = Math.floor((Date.now() - new Date(iso).getTime()) / 60_000);
  if (minutes < 1) return 'just now';
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}

const CaseRow = memo(function CaseRow({
  item,
  onOpen,
}: {
  item: CaseSummary;
  onOpen: (caseId: string) => void;
}) {
  const urgent = item.status === 'URGENT';
  return (
    <Pressable onPress={() => onOpen(item.caseId)} accessibilityRole="button">
      <Card className="mb-3">
        <View className="flex-row items-center justify-between">
          <Text variant="overline" className={urgent ? 'text-danger' : undefined}>
            {urgent ? 'Urgent' : 'Open'}
          </Text>
          <Text variant="caption" className={item.overdue ? 'text-danger' : undefined}>
            {when(item.openedAt)}
          </Text>
        </View>

        {item.overdue && (
          <View className="mt-2 self-start rounded-full bg-danger/15 px-3 py-1">
            <Text variant="caption" className="text-danger">
              Past the 24-hour commitment — {item.ageHours}h open
            </Text>
          </View>
        )}

        <Text variant="bodyStrong" className="mt-2">
          {item.targetUsername ?? 'Unknown account'}
        </Text>

        <Text variant="caption" className="mt-1 text-muted">
          {item.distinctReporters} {item.distinctReporters === 1 ? 'reporter' : 'reporters'} · weight{' '}
          {item.weightedScore.toFixed(1)}
          {item.autoHidden ? ' · hidden pending review' : ''}
        </Text>

        {item.priorSanctions > 0 && (
          <Text variant="caption" className="mt-1 text-primary">
            {item.priorSanctions} prior action{item.priorSanctions === 1 ? '' : 's'} on this account
          </Text>
        )}
      </Card>
    </Pressable>
  );
});
