-- User-uploaded avatars.
--
-- Run after upgrade-2026-5-outbox-and-declines.sql. Idempotent.

BEGIN;

-- --------------------------------------------------------------------------
-- Avatars become something the gamer uploads
-- --------------------------------------------------------------------------
-- The `avatars` table was a catalogue of pre-drawn pictures, some of which were sold.
-- Selling a picture that every other user also has is a weak proposition, and it left the
-- product with no way for anyone to look like themselves. Uploads replace it; what gets
-- sold instead is frames and banners, which decorate an avatar rather than being one.
--
-- `avatar` (the uuid pointing into the catalogue) is deliberately left in place. Removing
-- it in the same change as adding these would mean one migration that both adds a feature
-- and destroys the data behind the old one, with no way to run half of it. It goes when
-- the cosmetics catalogue lands and there is something for those rows to become.

ALTER TABLE gamebuddy.gamer
    -- The object key inside the bucket, not a URL. Which bucket and which host serve it
    -- are deployment concerns that change (r2.dev today, a custom domain later); a stored
    -- URL would bake today's answer into every row and need rewriting when it moves.
    ADD COLUMN IF NOT EXISTS avatar_key VARCHAR(255);

ALTER TABLE gamebuddy.gamer
    -- NULL when nothing has been uploaded. Otherwise PENDING, APPROVED or REJECTED.
    --
    -- PENDING and REJECTED both mean "not visible to anyone else". They are distinct
    -- because the owner should be told which one applies: an image waiting on a human is
    -- a delay, an image that was refused is a decision, and showing the same message for
    -- both means one of the two is a lie.
    ADD COLUMN IF NOT EXISTS avatar_status VARCHAR(16);

ALTER TABLE gamebuddy.gamer
    DROP CONSTRAINT IF EXISTS gamer_avatar_status_check;

ALTER TABLE gamebuddy.gamer
    ADD CONSTRAINT gamer_avatar_status_check
    CHECK (avatar_status IS NULL OR avatar_status IN ('PENDING', 'APPROVED', 'REJECTED'));

-- The moderation queue reads this: everything a human still has to look at, oldest first.
-- Partial, because PENDING is a small and shrinking slice of the table while APPROVED
-- grows without bound, and an index over both would be mostly rows nobody queries.
CREATE INDEX IF NOT EXISTS idx_gamer_avatar_pending
    ON gamebuddy.gamer (last_modified_date)
    WHERE avatar_status = 'PENDING';

-- --------------------------------------------------------------------------
-- Default avatars replace the old catalogue
-- --------------------------------------------------------------------------
-- The previous eight rows held bare filenames — `avatar-01.png` — for art that was never
-- hosted anywhere, so every one of them resolved to nothing and the client fell back to a
-- monogram. There is real art now (default-avatars/, generated by the script in there),
-- it lives in the media bucket, and the rows hold object keys.
--
-- Anyone who picked one of the old eight is moved to the same-numbered new one rather
-- than being reset. They chose that slot; the picture behind it has simply become a real
-- picture.

WITH remap(old_id, new_id) AS (
    VALUES
        ('3f74a7c2-e6b5-544b-b44e-eedd80f31a5c'::uuid, 'fe6bf0f4-5a02-543d-a646-a56f058492d0'::uuid),
        ('d0b9c903-cdc7-5e19-a45f-8c1fee9ea94c'::uuid, '5e4d0987-2c83-5df1-a31f-9dda325f85f9'::uuid),
        ('0091dfff-e393-5eaf-852d-e2b273039a65'::uuid, 'c74909e0-afac-5bc4-aecd-9b8ee13107ee'::uuid),
        ('f2de4558-bfef-5c89-9a04-6bc3a998938e'::uuid, 'd65a6954-f77e-5052-896c-f6589f4ecd68'::uuid),
        ('c43f9a1f-6f10-5145-8637-b277b0d9b16c'::uuid, 'b9590ea7-ed4d-5716-9d71-d5c5d0e322ba'::uuid),
        ('7321abf2-a3e7-5aac-ac4f-32a9e1caef6f'::uuid, '8461bc85-b3e8-570c-b309-1bd34148b518'::uuid),
        ('6e78186a-b404-5f29-a64d-bd7fd149c55f'::uuid, 'f0778fd2-4149-5205-a334-c0076f289b1b'::uuid),
        ('7510978e-abb1-5b20-b242-7eb9eaeb7534'::uuid, '2ddb464c-a728-58ee-83d8-68a2fb35bd4b'::uuid)
)
UPDATE gamebuddy.gamer g
SET avatar = remap.new_id
FROM remap
WHERE g.avatar = remap.old_id
  AND EXISTS (SELECT 1 FROM gamebuddy.avatars a WHERE a.id = remap.new_id);

-- The paid ones go too. Avatars stopped being merchandise when uploads landed: what gets
-- sold now is frames and banners, which decorate an avatar rather than being one. Nothing
-- was ever bought — this is a launch that has not happened — so no purchase is being
-- destroyed here, and bought_avatars is emptied with them.
DELETE FROM gamebuddy.bought_avatars
WHERE avatar_id IN (SELECT id FROM gamebuddy.avatars WHERE is_special);

DELETE FROM gamebuddy.avatars
WHERE image NOT LIKE 'default-avatars/%'
  AND NOT EXISTS (SELECT 1 FROM gamebuddy.gamer g WHERE g.avatar = avatars.id);

COMMIT;
