-- Eight more frames and eight more banners, and the shelf renumbered around them.
--
-- Run after upgrade-2026-34-super-likes.sql. Idempotent.
--
-- The Season Pass placeholder was dropped — there is no level or XP system for a pass to
-- progress along, so the card promised something nobody was going to build. The shop needed
-- more to sell rather than more to promise, and this is that: four static frames, four
-- animated ones, and eight banners drawn around game genres rather than abstract texture.
-- All of it is generated by cosmetics/generate.py from primitives, so none of it carries a
-- licence.
--
-- Ids are uuid5(NAMESPACE_DNS, asset_key), which is how every other row in the catalogue
-- was minted — see seed-local.sql. That means an environment can compute them rather than
-- copy them, and every environment agrees.
--
-- NOTE ON CONFLICTS: this keys on asset_key, not id. Production was populated out of band,
-- and asset_key is what an item actually *is* — it addresses the art on the CDN and it
-- carries a unique index (idx_cosmetic_asset_key, upgrade-2026-7). Keying on id would let a
-- row with the same art and a different id reach the unique index and raise, at which point
-- the migration has failed for the one case it was written to survive.
--
-- The art has to be uploaded before this runs, or the shelf shows sixteen broken images
-- until it is:
--     python cosmetics/generate.py && tools/upload-assets.sh frames banners

BEGIN;

INSERT INTO gamebuddy.cosmetic (id, kind, name, asset_key, animated, price, sort_order, membership_only, created_date) VALUES
  ('1b92c03c-e367-509a-96bf-eae0b7eb9c86', 'FRAME', 'Ticker', 'frames/frame-ticker.png', false, 250, 4, false, now()),
  ('05f5e4a3-c9b8-5dd0-8432-f55ce3a9fee5', 'FRAME', 'Scope', 'frames/frame-scope.png', false, 300, 5, false, now()),
  ('62e2927e-9e17-5cc3-b0ed-a61363fecc34', 'FRAME', 'Hazard', 'frames/frame-hazard.png', false, 350, 6, false, now()),
  ('0773088f-2bbe-5674-b8b9-12ee13d4b4ab', 'FRAME', 'Hive', 'frames/frame-hive.png', false, 400, 7, false, now()),
  ('5cca8449-895c-5fec-aadd-6d78ff66d797', 'FRAME', 'Frost', 'frames/frame-frost.webp', true, 700, 9, false, now()),
  ('28b357fc-34c8-515d-b0b5-d4b1b6364d2f', 'FRAME', 'Radar', 'frames/frame-radar.webp', true, 850, 11, false, now()),
  ('57ebafa3-efdd-5d4a-97ec-abab3c0c8ff7', 'FRAME', 'Comet', 'frames/frame-comet.webp', true, 1000, 14, false, now()),
  ('06cc2ed3-c81a-545f-8326-08ad8b1f56fa', 'FRAME', 'Glitch', 'frames/frame-glitch.webp', true, 1300, 16, false, now()),
  ('68211f9e-a59d-542f-a84a-069c06ebc4e5', 'BANNER', 'Overworld', 'banners/banner-overworld.jpg', false, 150, 2, false, now()),
  ('f5bde1b9-bf9f-5267-a345-20a47766df23', 'BANNER', 'Dungeon', 'banners/banner-dungeon.jpg', false, 250, 4, false, now()),
  ('06ef4e5a-f087-55d4-9fe4-4021317773f5', 'BANNER', 'WASD', 'banners/banner-wasd.jpg', false, 350, 6, false, now()),
  ('611ccbc1-0023-5034-8bbc-d001e50d5ca8', 'BANNER', 'Gamepad', 'banners/banner-gamepad.jpg', false, 450, 8, false, now()),
  ('049eebbd-ed44-5b0e-b020-5cfe0981c153', 'BANNER', 'Chicane', 'banners/banner-chicane.jpg', false, 550, 10, false, now()),
  ('62f866ae-4469-518f-b559-8de5665e68b4', 'BANNER', 'Minimap', 'banners/banner-minimap.jpg', false, 650, 12, false, now()),
  ('8061631c-015e-520f-bafb-38fef6f1924d', 'BANNER', 'Tabletop', 'banners/banner-tabletop.jpg', false, 700, 13, false, now()),
  ('ab747ebe-46af-5103-8d42-e5396041b1eb', 'BANNER', 'Zone', 'banners/banner-zone.jpg', false, 900, 15, false, now())
ON CONFLICT (asset_key) DO UPDATE
    SET kind = EXCLUDED.kind,
        name = EXCLUDED.name,
        animated = EXCLUDED.animated,
        price = EXCLUDED.price,
        sort_order = EXCLUDED.sort_order,
        membership_only = EXCLUDED.membership_only;

-- Renumber what was already on the shelf so the new rows interleave by price instead of
-- landing in a block at the end. The store orders by (kind, sort_order) and nothing else —
-- see CosmeticRepository.findAllByOrderByKindAscSortOrderAsc.
--
-- Written out per asset_key rather than as `sort_order = price`, because Orbit and Toxic
-- are both 900 and the shelf has to have an opinion about which comes first.
UPDATE gamebuddy.cosmetic c
SET sort_order = v.sort_order
FROM (VALUES
  ('frames/frame-steel.png', 0),
  ('frames/frame-brand.png', 1),
  ('frames/frame-reticle.png', 2),
  ('frames/frame-bronze.png', 3),
  ('frames/frame-pulse.webp', 8),
  ('frames/frame-sweep.webp', 10),
  ('frames/frame-orbit.webp', 12),
  ('frames/frame-toxic.webp', 13),
  ('frames/frame-rotor.webp', 15),
  ('frames/frame-ember.webp', 17),
  ('banners/banner-hex.jpg', 0),
  ('banners/banner-crt.jpg', 1),
  ('banners/banner-bokeh.jpg', 3),
  ('banners/banner-circuit.jpg', 5),
  ('banners/banner-void.jpg', 7),
  ('banners/banner-arena.jpg', 9),
  ('banners/banner-dusk.jpg', 11),
  ('banners/banner-synthwave.jpg', 14)
) AS v(asset_key, sort_order)
WHERE c.asset_key = v.asset_key AND c.membership_only = false;

-- The two membership items are not on this shelf at all — the Gold screen shows them — so
-- they are moved out of the way rather than given a place in the ordering they no longer
-- take part in. Without this the Gold frame keeps sort_order 4 and collides with Ticker.
UPDATE gamebuddy.cosmetic
SET sort_order = 99
WHERE membership_only = true;

COMMIT;
