#!/usr/bin/env node
/**
 * Writes the resource caps for one Hetzner plan.
 *
 *   node qa/perf/plan.js cx33     -> qa/perf/plan.override.yml
 *   node qa/perf/plan.js uncapped
 *
 * The four SUT containers share one `cpuset`, because on Hetzner they share one box: the
 * database, the JVM, the model and Redis all contend for the same vCPUs, and giving each
 * container its own cores would measure a machine nobody is going to buy. The generator is
 * pinned to the cores left over.
 *
 * Verified specifications (hetzner.com, August 2026):
 *
 *   CAX11   2 vCPU  Ampere Altra (ARM64)   4 GB   40 GB NVMe   ~EUR 3.79/mo
 *   CX23    2 vCPU  Intel Xeon (shared)    4 GB   40 GB NVMe   ~EUR 3.99/mo
 *   CX33    4 vCPU  shared                 8 GB   80 GB NVMe   ~EUR 6.49/mo
 *
 * A caveat that has to travel with every CAX11 number: this host is x86_64. Pinning two
 * cores and 4 GB reproduces CAX11's *shape*, not an Ampere Altra core's speed. Treat the
 * CAX11 column as "what 2 cores and 4 GB does", and confirm on the real hardware for an
 * hour before buying — it costs about one euro cent.
 */

const fs = require('node:fs');
const path = require('node:path');

/**
 * Memory split across the four containers.
 *
 * The JVM takes MaxRAMPercentage=75 of whatever its container is given, so `backend` is
 * the number that decides the heap. Postgres gets enough for its shared buffers plus room
 * for the OS page cache to do the real caching. The model needs headroom for the ViT
 * weights the NSFW classifier loads lazily on the first upload — a limit that fits an idle
 * model service and not a working one produces an OOM kill on the first avatar.
 */
const PLANS = {
  cax11: {
    label: 'CAX11 — 2 vCPU Ampere ARM64, 4 GB',
    cpus: '0,1',
    generator: '8-15',
    mem: { postgres: '900m', backend: '2g', model: '900m', redis: '128m' },
    note: 'ARM64 in reality; shape only on this x86 host.',
  },
  cx23: {
    label: 'CX23 — 2 vCPU Intel, 4 GB',
    cpus: '0,1',
    generator: '8-15',
    mem: { postgres: '900m', backend: '2g', model: '900m', redis: '128m' },
  },
  cx33: {
    label: 'CX33 — 4 vCPU, 8 GB',
    cpus: '0-3',
    generator: '8-15',
    mem: { postgres: '2g', backend: '4g', model: '1600m', redis: '256m' },
  },
  uncapped: {
    label: 'Uncapped — the whole host, for a baseline shape',
    cpus: '0-7',
    generator: '8-15',
    mem: { postgres: '4g', backend: '6g', model: '3g', redis: '512m' },
  },
};

const name = (process.argv[2] || '').toLowerCase();
const plan = PLANS[name];
if (!plan) {
  console.error(`Usage: node qa/perf/plan.js <${Object.keys(PLANS).join('|')}>`);
  process.exit(1);
}

const services = Object.entries(plan.mem)
  .map(([svc, mem]) => `  ${svc}:\n    cpuset: "${plan.cpus}"\n    mem_limit: ${mem}\n    memswap_limit: ${mem}\n`)
  .join('');

const yaml = `# GENERATED by qa/perf/plan.js — do not edit.
#
# ${plan.label}
# SUT cores: ${plan.cpus}   generator cores: ${plan.generator}
${plan.note ? `# ${plan.note}\n` : ''}#
# memswap_limit equals mem_limit on purpose: without it Docker allows an equal amount of
# swap on top, so a container "limited" to 2 GB quietly uses 4 and the memory answer is
# wrong in the one direction that matters.

name: gamebuddy-perf

services:
${services}`;

const out = path.join(__dirname, 'plan.override.yml');
fs.writeFileSync(out, yaml);

fs.writeFileSync(path.join(__dirname, 'plan.current.json'), JSON.stringify({ name, ...plan }, null, 2));

console.log(`${plan.label}`);
console.log(`  SUT cores      ${plan.cpus}`);
console.log(`  generator      ${plan.generator}`);
console.log(`  memory         ${Object.entries(plan.mem).map(([k, v]) => `${k}=${v}`).join('  ')}`);
console.log(`\nWrote ${out}`);
