"""Exports a synthetic population as SQL and CSV.

A warning that belongs at the top of the file rather than in a README
--------------------------------------------------------------------
These rows are **training fixtures, not users**. If they are inserted into the live
``schauth.gamer`` table they become swipeable: a real person opens the app, is shown a
profile that will never answer, and the product looks dead in exactly the way seeding was
supposed to prevent. Worse, a fake profile that a real user can message is a fake profile
they can be deceived by, which is the thing dating and matching apps get investigated for.

So the default target is a **separate schema** (``schtrain``), which the recommender can
train from and the API never serves. ``--schema schauth`` is offered because seeding a
local or staging database is legitimate, but it is opt-in, and every generated account
carries the marker below so a mistake stays reversible:

* email domain ``@bot.gamebuddy.invalid`` — ``.invalid`` is reserved by RFC 2606 and can
  never be registered, so these addresses cannot collide with a real signup or be mailed;
* ``pwd`` set to a string that is not a valid bcrypt hash, so no one can log in as one;
* ``DELETE FROM ... WHERE email LIKE '%@bot.gamebuddy.invalid'`` removes every trace.

If bot profiles are ever deliberately shown to real users, that is a product and legal
decision, and it needs disclosure in the app — not a seed script.
"""

from __future__ import annotations

import csv
import uuid
from collections import Counter
from pathlib import Path

from .catalogue import ALL_GAMES, ALL_KEYWORDS
from .population import Population

BOT_EMAIL_DOMAIN = "bot.gamebuddy.invalid"


def is_seed_account(email: str | None) -> bool:
    """Whether an address belongs to a generated account rather than a person.

    The single definition of that question. It is asked in three places that must agree —
    the exporter deciding what to train on, the trainer deciding what may be recommended,
    and the SQL that deletes the seed — and a mismatch between any two of them is silent:
    accounts that are trained on but never served, or served but never trained, or left
    behind by a cleanup that believed it had removed everything.
    """
    return bool(email) and email.lower().endswith("@" + BOT_EMAIL_DOMAIN)

#: Deliberately not a bcrypt hash. Spring Security's BCryptPasswordEncoder rejects any
#: string that does not start with $2a/$2b/$2y, so no password can ever match this.
UNUSABLE_PASSWORD = "{noop-disabled}synthetic-training-account-no-login"


def _sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _stable_uuid(namespace: str, name: str) -> str:
    """Deterministic ids so re-running the export does not duplicate rows."""
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"gamebuddy:{namespace}:{name}"))


def write_sql(population: Population, path: Path | str, *, schema: str = "schtrain") -> Path:
    """Writes an idempotent seed script.

    Every statement is ``ON CONFLICT DO NOTHING`` so the script can be re-run without
    hand-cleaning the database first, which is the difference between a seed you use and
    one you run once and abandon.
    """
    path = Path(path)
    lines: list[str] = [
        "-- GameBuddy synthetic training population.",
        "-- Generated by gamebuddy_model.seed; do not edit by hand.",
        f"-- Accounts are identifiable by their @{BOT_EMAIL_DOMAIN} email domain.",
        "",
        "BEGIN;",
        "",
        f"CREATE SCHEMA IF NOT EXISTS {schema};",
        "",
    ]

    if schema != "schauth":
        lines += [
            "-- Standalone tables, so a training population never touches the live ones.",
            f"CREATE TABLE IF NOT EXISTS {schema}.games (",
            "    game_id VARCHAR(255) PRIMARY KEY, game_name VARCHAR(255) NOT NULL,",
            "    category VARCHAR(255), is_popular BOOLEAN DEFAULT FALSE);",
            f"CREATE TABLE IF NOT EXISTS {schema}.keywords (",
            "    id UUID PRIMARY KEY, keyword_name VARCHAR(255) NOT NULL);",
            f"CREATE TABLE IF NOT EXISTS {schema}.gamer (",
            "    user_id VARCHAR(255) PRIMARY KEY, username VARCHAR(255) UNIQUE,",
            "    email VARCHAR(255) UNIQUE NOT NULL, age INTEGER, country VARCHAR(255),",
            "    gender VARCHAR(255), pwd VARCHAR(255), is_blocked BOOLEAN DEFAULT FALSE,",
            "    coin INTEGER DEFAULT 0, role VARCHAR(32) DEFAULT 'USER',",
            "    last_active_at TIMESTAMPTZ, version BIGINT DEFAULT 0);",
            # Column named user_id, matching gamebuddy.gamer_platform in the live schema —
            # the join tables either side of it use gamer_id, and getting this wrong is
            # only discovered when the seed is pointed at schauth.
            f"CREATE TABLE IF NOT EXISTS {schema}.gamer_platform (",
            f"    user_id VARCHAR(255) REFERENCES {schema}.gamer(user_id) ON DELETE CASCADE,",
            "    platform VARCHAR(16) NOT NULL, PRIMARY KEY (user_id, platform));",
            f"CREATE TABLE IF NOT EXISTS {schema}.gamer_games_join (",
            f"    gamer_id VARCHAR(255) REFERENCES {schema}.gamer(user_id) ON DELETE CASCADE,",
            f"    game_id VARCHAR(255) REFERENCES {schema}.games(game_id) ON DELETE CASCADE,",
            "    PRIMARY KEY (gamer_id, game_id));",
            f"CREATE TABLE IF NOT EXISTS {schema}.gamer_keywords_join (",
            f"    gamer_id VARCHAR(255) REFERENCES {schema}.gamer(user_id) ON DELETE CASCADE,",
            f"    keyword_id UUID REFERENCES {schema}.keywords(id) ON DELETE CASCADE,",
            "    PRIMARY KEY (gamer_id, keyword_id));",
            f"CREATE TABLE IF NOT EXISTS {schema}.approved_matches (",
            f"    user_id VARCHAR(255) REFERENCES {schema}.gamer(user_id) ON DELETE CASCADE,",
            f"    matched_id VARCHAR(255) REFERENCES {schema}.gamer(user_id) ON DELETE CASCADE,",
            "    PRIMARY KEY (user_id, matched_id));",
            "",
        ]

    # -- catalogue ---------------------------------------------------------
    game_ids = {name: _stable_uuid("game", name) for name, _ in ALL_GAMES}
    keyword_ids = {kw: _stable_uuid("keyword", kw) for kw in ALL_KEYWORDS}

    # One pass rather than a scan of every gamer for every title: the nested version was
    # quadratic and turned into a visible stall once populations reached five figures.
    plays = Counter(name for gamer in population.gamers for name in gamer.games)
    threshold = len(population.gamers) * 0.08
    popular = {name for name, count in plays.items() if count > threshold}

    lines.append("-- Games")
    for name, category in ALL_GAMES:
        lines.append(
            f"INSERT INTO {schema}.games (game_id, game_name, category, is_popular) VALUES "
            f"({_sql_str(game_ids[name])}, {_sql_str(name)}, {_sql_str(category)}, "
            f"{'TRUE' if name in popular else 'FALSE'}) ON CONFLICT (game_id) DO NOTHING;"
        )

    lines += ["", "-- Keywords"]
    for kw in ALL_KEYWORDS:
        lines.append(
            f"INSERT INTO {schema}.keywords (id, keyword_name) VALUES "
            f"({_sql_str(keyword_ids[kw])}, {_sql_str(kw)}) ON CONFLICT (id) DO NOTHING;"
        )

    # -- gamers ------------------------------------------------------------
    lines += ["", "-- Synthetic gamers"]
    for gamer in population.gamers:
        # Relative to NOW() rather than a baked timestamp, so a seed loaded next month
        # still has people who look recently active — the product's "online now" filter
        # reads a 15-minute window and an absolute time would make every bot look dead.
        last_active = f"NOW() - INTERVAL '{gamer.last_active_minutes_ago} minutes'"
        lines.append(
            f"INSERT INTO {schema}.gamer (user_id, username, email, age, country, gender, "
            "pwd, is_blocked, coin, role, last_active_at, version) VALUES ("
            f"{_sql_str(gamer.user_id)}, {_sql_str(gamer.username)}, "
            f"{_sql_str(gamer.email)}, {gamer.age}, {_sql_str(gamer.country)}, "
            f"{_sql_str(gamer.gender)}, {_sql_str(UNUSABLE_PASSWORD)}, FALSE, 0, 'USER', "
            f"{last_active}, 0) ON CONFLICT (user_id) DO NOTHING;"
        )

    lines += ["", "-- Profiles"]
    for gamer in population.gamers:
        for game in gamer.games:
            lines.append(
                f"INSERT INTO {schema}.gamer_games_join (gamer_id, game_id) VALUES "
                f"({_sql_str(gamer.user_id)}, {_sql_str(game_ids[game])}) ON CONFLICT DO NOTHING;"
            )
        for kw in gamer.keywords:
            lines.append(
                f"INSERT INTO {schema}.gamer_keywords_join (gamer_id, keyword_id) VALUES "
                f"({_sql_str(gamer.user_id)}, {_sql_str(keyword_ids[kw])}) ON CONFLICT DO NOTHING;"
            )
        for platform in gamer.platforms:
            lines.append(
                f"INSERT INTO {schema}.gamer_platform (user_id, platform) VALUES "
                f"({_sql_str(gamer.user_id)}, {_sql_str(platform)}) ON CONFLICT DO NOTHING;"
            )

    # Matches are stored both ways round, because the backend reads the owning side from
    # whichever gamer is asking.
    lines += ["", "-- Mutual matches (both directions)"]
    ids = population.user_ids
    for left, right in population.mutual_pairs:
        a, b = ids[left], ids[right]
        for x, y in ((a, b), (b, a)):
            lines.append(
                f"INSERT INTO {schema}.approved_matches (user_id, matched_id) VALUES "
                f"({_sql_str(x)}, {_sql_str(y)}) ON CONFLICT DO NOTHING;"
            )

    lines += ["", "COMMIT;", ""]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_csv(population: Population, directory: Path | str) -> dict[str, Path]:
    """Writes the same population as CSV, for training without a database.

    Three files rather than one wide frame: the original kept games and keywords as
    comma-joined strings inside a single cell, which then had to be split back out with a
    separator that also appears inside game titles.
    """
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}

    paths["gamers"] = directory / "gamers.csv"
    with paths["gamers"].open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["user_id", "username", "email", "age", "country", "gender",
                         "platforms", "last_active_minutes_ago"])
        for g in population.gamers:
            writer.writerow([g.user_id, g.username, g.email, g.age, g.country, g.gender,
                             "|".join(sorted(g.platforms)), g.last_active_minutes_ago])

    paths["profiles"] = directory / "profiles.csv"
    with paths["profiles"].open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["user_id", "kind", "value"])
        for g in population.gamers:
            for game in sorted(g.games):
                writer.writerow([g.user_id, "game", game])
            for kw in sorted(g.keywords):
                writer.writerow([g.user_id, "keyword", kw])

    ids = population.user_ids

    paths["matches"] = directory / "matches.csv"
    with paths["matches"].open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["user_id", "matched_id"])
        for left, right in population.mutual_pairs:
            writer.writerow([ids[left], ids[right]])

    paths["interactions"] = directory / "interactions.csv"
    with paths["interactions"].open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["user_id", "target_id", "decision"])
        # Streamed straight from the generator rather than sorted into memory first: at
        # twenty thousand gamers this is several million rows, and sorting them bought
        # nothing that the deterministic seed does not already give.
        writer.writerows(population.interactions())

    return paths
