"""Exports a synthetic population as SQL and CSV.

A warning that belongs at the top of the file rather than in a README
--------------------------------------------------------------------
These rows are **training fixtures, not users**. If they are inserted into the live
``schauth.gamer`` table they become swipeable: a real person opens the app, is shown a
profile that will never answer, and the product looks dead in exactly the way seeding was
supposed to prevent. Worse, a fake profile that a real user can message is a fake profile
they can be deceived by, which is the thing dating and matching apps get investigated for.

So the default target is a **separate schema** (``schtrain``), which the recommender can
train from and the API never serves. ``--schema schauth`` is offered because seeding a
local or staging database is legitimate, but it is opt-in, and every generated account
carries the marker below so a mistake stays reversible:

* email domain ``@bot.gamebuddy.invalid`` — ``.invalid`` is reserved by RFC 2606 and can
  never be registered, so these addresses cannot collide with a real signup or be mailed;
* ``pwd`` set to a string that is not a valid bcrypt hash, so no one can log in as one;
* ``DELETE FROM ... WHERE email LIKE '%@bot.gamebuddy.invalid'`` removes every trace.

If bot profiles are ever deliberately shown to real users, that is a product and legal
decision, and it needs disclosure in the app — not a seed script.
"""

from __future__ import annotations

import csv
import uuid
from pathlib import Path

from .catalogue import ALL_GAMES, ALL_KEYWORDS
from .population import Population

BOT_EMAIL_DOMAIN = "bot.gamebuddy.invalid"

#: Deliberately not a bcrypt hash. Spring Security's BCryptPasswordEncoder rejects any
#: string that does not start with $2a/$2b/$2y, so no password can ever match this.
UNUSABLE_PASSWORD = "{noop-disabled}synthetic-training-account-no-login"


def _sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _stable_uuid(namespace: str, name: str) -> str:
    """Deterministic ids so re-running the export does not duplicate rows."""
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"gamebuddy:{namespace}:{name}"))


def write_sql(population: Population, path: Path | str, *, schema: str = "schtrain") -> Path:
    """Writes an idempotent seed script.

    Every statement is ``ON CONFLICT DO NOTHING`` so the script can be re-run without
    hand-cleaning the database first, which is the difference between a seed you use and
    one you run once and abandon.
    """
    path = Path(path)
    lines: list[str] = [
        "-- GameBuddy synthetic training population.",
        "-- Generated by gamebuddy_model.seed; do not edit by hand.",
        f"-- Accounts are identifiable by their @{BOT_EMAIL_DOMAIN} email domain.",
        "",
        "BEGIN;",
        "",
        f"CREATE SCHEMA IF NOT EXISTS {schema};",
        "",
    ]

    if schema != "schauth":
        lines += [
            "-- Standalone tables, so a training population never touches the live ones.",
            f"CREATE TABLE IF NOT EXISTS {schema}.games (",
            "    game_id VARCHAR(255) PRIMARY KEY, game_name VARCHAR(255) NOT NULL,",
            "    category VARCHAR(255), is_popular BOOLEAN DEFAULT FALSE);",
            f"CREATE TABLE IF NOT EXISTS {schema}.keywords (",
            "    id UUID PRIMARY KEY, keyword_name VARCHAR(255) NOT NULL);",
            f"CREATE TABLE IF NOT EXISTS {schema}.gamer (",
            "    user_id VARCHAR(255) PRIMARY KEY, username VARCHAR(255) UNIQUE,",
            "    email VARCHAR(255) UNIQUE NOT NULL, age INTEGER, country VARCHAR(255),",
            "    gender VARCHAR(255), pwd VARCHAR(255), is_blocked BOOLEAN DEFAULT FALSE,",
            "    coin INTEGER DEFAULT 0, role VARCHAR(32) DEFAULT 'USER', version BIGINT DEFAULT 0);",
            f"CREATE TABLE IF NOT EXISTS {schema}.gamer_games_join (",
            f"    gamer_id VARCHAR(255) REFERENCES {schema}.gamer(user_id) ON DELETE CASCADE,",
            f"    game_id VARCHAR(255) REFERENCES {schema}.games(game_id) ON DELETE CASCADE,",
            "    PRIMARY KEY (gamer_id, game_id));",
            f"CREATE TABLE IF NOT EXISTS {schema}.gamer_keywords_join (",
            f"    gamer_id VARCHAR(255) REFERENCES {schema}.gamer(user_id) ON DELETE CASCADE,",
            f"    keyword_id UUID REFERENCES {schema}.keywords(id) ON DELETE CASCADE,",
            "    PRIMARY KEY (gamer_id, keyword_id));",
            f"CREATE TABLE IF NOT EXISTS {schema}.approved_matches (",
            f"    user_id VARCHAR(255) REFERENCES {schema}.gamer(user_id) ON DELETE CASCADE,",
            f"    matched_id VARCHAR(255) REFERENCES {schema}.gamer(user_id) ON DELETE CASCADE,",
            "    PRIMARY KEY (user_id, matched_id));",
            "",
        ]

    # -- catalogue ---------------------------------------------------------
    game_ids = {name: _stable_uuid("game", name) for name, _ in ALL_GAMES}
    keyword_ids = {kw: _stable_uuid("keyword", kw) for kw in ALL_KEYWORDS}

    played = {g for gamer in population.gamers for g in gamer.games}
    popular = {name for name in played if sum(1 for x in population.gamers if name in x.games) > len(population.gamers) * 0.08}

    lines.append("-- Games")
    for name, category in ALL_GAMES:
        lines.append(
            f"INSERT INTO {schema}.games (game_id, game_name, category, is_popular) VALUES "
            f"({_sql_str(game_ids[name])}, {_sql_str(name)}, {_sql_str(category)}, "
            f"{'TRUE' if name in popular else 'FALSE'}) ON CONFLICT (game_id) DO NOTHING;"
        )

    lines += ["", "-- Keywords"]
    for kw in ALL_KEYWORDS:
        lines.append(
            f"INSERT INTO {schema}.keywords (id, keyword_name) VALUES "
            f"({_sql_str(keyword_ids[kw])}, {_sql_str(kw)}) ON CONFLICT (id) DO NOTHING;"
        )

    # -- gamers ------------------------------------------------------------
    lines += ["", "-- Synthetic gamers"]
    for gamer in population.gamers:
        lines.append(
            f"INSERT INTO {schema}.gamer (user_id, username, email, age, country, gender, "
            "pwd, is_blocked, coin, role, version) VALUES ("
            f"{_sql_str(gamer.user_id)}, {_sql_str(gamer.username)}, "
            f"{_sql_str(gamer.email)}, {gamer.age}, {_sql_str(gamer.country)}, "
            f"{_sql_str(gamer.gender)}, {_sql_str(UNUSABLE_PASSWORD)}, FALSE, 0, 'USER', 0) "
            "ON CONFLICT (user_id) DO NOTHING;"
        )

    lines += ["", "-- Profiles"]
    for gamer in population.gamers:
        for game in gamer.games:
            lines.append(
                f"INSERT INTO {schema}.gamer_games_join (gamer_id, game_id) VALUES "
                f"({_sql_str(gamer.user_id)}, {_sql_str(game_ids[game])}) ON CONFLICT DO NOTHING;"
            )
        for kw in gamer.keywords:
            lines.append(
                f"INSERT INTO {schema}.gamer_keywords_join (gamer_id, keyword_id) VALUES "
                f"({_sql_str(gamer.user_id)}, {_sql_str(keyword_ids[kw])}) ON CONFLICT DO NOTHING;"
            )

    # Matches are stored both ways round, because the backend reads the owning side from
    # whichever gamer is asking.
    lines += ["", "-- Mutual matches (both directions)"]
    for pair in sorted(tuple(sorted(p)) for p in population.mutual):
        a, b = pair
        for x, y in ((a, b), (b, a)):
            lines.append(
                f"INSERT INTO {schema}.approved_matches (user_id, matched_id) VALUES "
                f"({_sql_str(x)}, {_sql_str(y)}) ON CONFLICT DO NOTHING;"
            )

    lines += ["", "COMMIT;", ""]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_csv(population: Population, directory: Path | str) -> dict[str, Path]:
    """Writes the same population as CSV, for training without a database.

    Three files rather than one wide frame: the original kept games and keywords as
    comma-joined strings inside a single cell, which then had to be split back out with a
    separator that also appears inside game titles.
    """
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}

    paths["gamers"] = directory / "gamers.csv"
    with paths["gamers"].open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["user_id", "username", "email", "age", "country", "gender", "is_minor"])
        for g in population.gamers:
            writer.writerow([g.user_id, g.username, g.email, g.age, g.country, g.gender, g.is_minor])

    paths["profiles"] = directory / "profiles.csv"
    with paths["profiles"].open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["user_id", "kind", "value"])
        for g in population.gamers:
            for game in sorted(g.games):
                writer.writerow([g.user_id, "game", game])
            for kw in sorted(g.keywords):
                writer.writerow([g.user_id, "keyword", kw])

    paths["matches"] = directory / "matches.csv"
    with paths["matches"].open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["user_id", "matched_id"])
        for pair in sorted(tuple(sorted(p)) for p in population.mutual):
            writer.writerow(list(pair))

    paths["interactions"] = directory / "interactions.csv"
    with paths["interactions"].open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["user_id", "target_id", "decision"])
        for a, b in sorted(population.likes):
            writer.writerow([a, b, "LIKE"])
        for a, b in sorted(population.passes):
            writer.writerow([a, b, "PASS"])

    return paths
