import { useEffect, useMemo } from 'react';
import { StyleSheet, View } from 'react-native';
import Animated, {
  Easing,
  interpolate,
  useAnimatedStyle,
  useSharedValue,
  withTiming,
  type SharedValue,
} from 'react-native-reanimated';
import { useThemeColors } from '../theme';

/**
 * A particle burst — light thrown off a moment worth marking.
 *
 * **Why this is not Lottie.** It used to be: `assets/lottie/match-burst.json`, generated by
 * a Python script, 24 layers at 60fps. It mounted, the JSON parsed, and nothing ever drew —
 * no error, just an empty panel. That cost a session and was never solved. This replaces it
 * outright, and `lottie-react-native` went with it. Reanimated is already a dependency, is
 * already how everything else in the app moves, and cannot fail silently in the same way,
 * because the particles are real views the inspector can see.
 *
 * **One shared value, not one per particle.** `progress` runs 0→1 once and every particle
 * derives its own position from it, staggered by a per-particle `delay` baked into the spec.
 * Twenty-odd independent timings would be twenty-odd chances for the UI thread to schedule
 * them apart; one timing cannot desynchronise from itself.
 *
 * **Each particle is its own component.** That is not decoration — `useAnimatedStyle` is a
 * hook, and a hook called in a loop inside one component would make the hook count depend on
 * `count`, so changing the prop would crash React. As children, the count is free to move.
 *
 * Two of this project's documented traps apply directly here, both silent:
 * - `className` never goes on an `Animated.View` (see the block comment in `MatchOverlay`).
 *   Nothing in this file uses NativeWind at all; it is styles the whole way down.
 * - An animated `transform` *replaces* a static one rather than merging with it. So the
 *   static styles below carry no `transform` key, and every particle's full transform is
 *   declared inside its worklet.
 */

type BurstProps = {
  /**
   * A counter, not a boolean. Incrementing it replays; the value itself means nothing.
   *
   * A boolean would need to be flipped back to false before it could fire again, and the
   * caller would own that reset — which is how you end up with a burst that plays once per
   * app launch. Mounting also counts as a play, so a burst that appears with its overlay
   * fires without the caller doing anything.
   */
  play: number;
  /** Defaults to the accent — like, match, admirer. Pass `colors.gold` for coins. */
  color?: string;
  /** How far the furthest particle travels, in px. The burst is centred on its parent. */
  radius?: number;
  particles?: number;
  /** Milliseconds for the whole thing, stagger included. */
  duration?: number;
};

export function Burst({
  play,
  color,
  radius = 170,
  particles = 22,
  duration = 1100,
}: BurstProps) {
  const colors = useThemeColors();
  const tint = color ?? colors.accent;

  const progress = useSharedValue(0);
  const specs = useMemo(() => buildSpecs(particles, radius), [particles, radius]);

  useEffect(() => {
    progress.value = 0;
    progress.value = withTiming(1, {
      duration,
      // Linear on purpose. Each particle eases its *own* travel inside its worklet, and
      // easing the driver as well would compound the two into a burst that crawls at the end.
      easing: Easing.linear,
    });
  }, [play, progress, duration]);

  return (
    <View style={StyleSheet.absoluteFill} pointerEvents="none">
      <View style={styles.centre}>
        <Ring progress={progress} color={tint} radius={radius} />
        {specs.map((spec, index) => (
          <Particle key={index} progress={progress} spec={spec} color={tint} />
        ))}
      </View>
    </View>
  );
}

type ParticleSpec = {
  angle: number;
  distance: number;
  size: number;
  delay: number;
  /** Whether this one is white rather than the tint — a few sparks read as light, not paint. */
  pale: boolean;
  square: boolean;
};

/**
 * Evenly spaced angles with deterministic jitter.
 *
 * Even spacing alone looks like a clock face and pure randomness leaves bald patches, so
 * each particle starts at its slot and is nudged by up to half a slot. The jitter comes from
 * a hash of the index rather than `Math.random`, so a given index always lands in the same
 * place — a burst that reshuffles on every render would flicker whenever the parent
 * re-renders mid-flight.
 */
function buildSpecs(count: number, radius: number): ParticleSpec[] {
  const slot = (Math.PI * 2) / count;

  return Array.from({ length: count }, (_, i) => ({
    angle: i * slot + (noise(i, 1) - 0.5) * slot,
    // Never the full radius for everything: a uniform distance draws a visible circle at the
    // end of the animation instead of a scatter.
    distance: radius * (0.55 + noise(i, 2) * 0.45),
    size: 5 + Math.round(noise(i, 3) * 7),
    // Capped well below 1 — a particle that starts at 0.9 has a tenth of the duration to
    // travel and arrives as a blink.
    delay: noise(i, 4) * 0.28,
    pale: noise(i, 5) > 0.65,
    square: noise(i, 6) > 0.5,
  }));
}

/** Deterministic 0..1 from an index and a salt. The usual fractional-sine hash. */
function noise(index: number, salt: number): number {
  const value = Math.sin(index * 127.1 + salt * 311.7) * 43758.5453;
  return value - Math.floor(value);
}

function Particle({
  progress,
  spec,
  color,
}: {
  progress: SharedValue<number>;
  spec: ParticleSpec;
  color: string;
}) {
  const animated = useAnimatedStyle(() => {
    // Each particle's own 0→1, starting when its delay elapses. Clamped rather than allowed
    // to go negative, so a delayed particle sits invisible at the centre instead of flying
    // inwards before it starts.
    const local = Math.min(Math.max((progress.value - spec.delay) / (1 - spec.delay), 0), 1);

    // Ease-out cubic: fast off the mark, drifting at the end. Particles that decelerate read
    // as thrown; linear ones read as a diagram.
    const travelled = 1 - Math.pow(1 - local, 3);
    const distance = spec.distance * travelled;

    return {
      opacity: interpolate(local, [0, 0.12, 0.7, 1], [0, 1, 1, 0]),
      transform: [
        { translateX: Math.cos(spec.angle) * distance },
        { translateY: Math.sin(spec.angle) * distance },
        { scale: interpolate(local, [0, 0.2, 1], [0.3, 1, 0.35]) },
        { rotate: `${local * 180 * (spec.square ? 1 : 0)}deg` },
      ],
    };
  });

  return (
    <Animated.View
      style={[
        styles.particle,
        {
          width: spec.size,
          height: spec.size,
          // A round particle is a spark and a square one is confetti. Mixing the two is what
          // keeps this from looking like a loading spinner coming apart.
          borderRadius: spec.square ? 1 : spec.size / 2,
          backgroundColor: spec.pale ? '#FFFFFF' : color,
          // Pulls the particle's own centre onto the origin. Without this every particle
          // hangs off the centre by half its size, which skews the whole burst down-right.
          marginLeft: -spec.size / 2,
          marginTop: -spec.size / 2,
        },
        animated,
      ]}
    />
  );
}

/**
 * The shockwave.
 *
 * A ring expanding ahead of the particles gives the burst an origin — without it the
 * particles read as appearing from nowhere rather than being thrown from a point. It leads
 * them deliberately: it is done by roughly the time the fastest particle catches up.
 */
function Ring({
  progress,
  color,
  radius,
}: {
  progress: SharedValue<number>;
  color: string;
  radius: number;
}) {
  const animated = useAnimatedStyle(() => {
    const local = Math.min(progress.value / 0.55, 1);
    const eased = 1 - Math.pow(1 - local, 3);

    return {
      opacity: interpolate(local, [0, 0.15, 1], [0, 0.5, 0]),
      transform: [{ scale: 0.1 + eased * 1.1 }],
    };
  });

  const size = radius * 2;

  return (
    <Animated.View
      style={[
        styles.ring,
        {
          width: size,
          height: size,
          borderRadius: radius,
          borderColor: color,
          marginLeft: -radius,
          marginTop: -radius,
        },
        animated,
      ]}
    />
  );
}

/**
 * `top: 50%` / `left: 50%` with zero size: every child is positioned from the exact centre of
 * the parent, so a particle's translate is its distance from the origin and nothing else.
 * Sizing this box instead would make every offset relative to a corner.
 */
const styles = StyleSheet.create({
  centre: {
    position: 'absolute',
    left: '50%',
    top: '50%',
    width: 0,
    height: 0,
  },
  particle: {
    position: 'absolute',
  },
  ring: {
    position: 'absolute',
    borderWidth: 2,
  },
});
