import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';
import { create } from 'zustand';
import { secureStorage } from '../session/storage';

/**
 * The app's four sound cues, named for what happened rather than for which file plays.
 *
 * Deliberately the same shape as `src/ui/haptics.ts`, down to the fire-and-forget contract
 * and the swallowed rejections, because the two are meant to be used together and a call
 * site that says `celebrate()` for one and `play('match.wav')` for the other will drift
 * apart within a month. `src/ui/feedback.ts` is the layer that fires both; prefer it.
 *
 * **Audio mode.** Configured once, on first use:
 *
 * - `playsInSilentMode: false` — the iOS silent switch wins. It defaults to `true`, which
 *   is right for a media app and wrong for every app that only makes UI noises. Someone who
 *   has physically flipped their phone to silent has said what they want.
 * - `interruptionMode: 'mixWithOthers'` — never duck, never pause. These cues are under a
 *   second long and a great many people swipe with music on; interrupting a track to
 *   announce a message would be an unambiguous bug.
 * - `shouldPlayInBackground: false` — nothing here should ever play with the app closed.
 *
 * The matching config-plugin entry in `app.json` turns off everything expo-audio would
 * otherwise add by default: `recordAudioAndroid`, `microphonePermission`, and both
 * background modes. Left at their defaults it would have added
 * `FOREGROUND_SERVICE_MEDIA_PLAYBACK`, a foreground `AudioControlsService`, an iOS `audio`
 * background mode and an `NSMicrophoneUsageDescription` — review-visible changes on an
 * existing Play listing, in exchange for four sub-second blips that need none of them. It
 * would also have requested `RECORD_AUDIO`, though that one is moot: `expo-image-picker`
 * two entries above already sets `microphonePermission: false`, which emits a
 * `tools:node="remove"` and strips it from the merged manifest regardless.
 *
 * **Verified against the merged manifest**, not assumed: with these flags the only thing
 * this module adds is `MODIFY_AUDIO_SETTINGS`, which comes from expo-audio's own library
 * manifest, is a normal permission rather than a runtime one, and cannot be configured away.
 *
 * The cues themselves are generated by `scripts/make-sounds.py` and are placeholders. See
 * that file before replacing them.
 */

const KEY = 'gamebuddy.soundEnabled';

type SoundState = {
  enabled: boolean;
  /** False until storage has been read. Nothing gates on it — see `load` below. */
  hydrated: boolean;
  load: () => Promise<void>;
  setEnabled: (enabled: boolean) => void;
};

/**
 * On by default, and unlike the theme preference this does **not** wait for hydration
 * before it is honoured.
 *
 * The reason is the failure mode. A theme read late paints the whole app in the wrong
 * colours, so `useScheme` blocks on it. A cue played in the first few hundred milliseconds
 * after launch, before storage answers, is at worst one unwanted blip — and blocking on it
 * would mean the first sound of a session is the one most likely to be swallowed.
 */
export const useSoundEnabled = create<SoundState>((set) => ({
  enabled: true,
  hydrated: false,

  load: async () => {
    const stored = await secureStorage.get(KEY);
    set({ enabled: stored !== 'off', hydrated: true });
  },

  setEnabled: (enabled) => {
    set({ enabled });
    // Not awaited, same as the theme preference: the switch should move on the same frame
    // as the tap, and a failed write costs the setting at next launch and nothing else.
    void secureStorage.set(KEY, enabled ? 'on' : 'off');
  },
}));

/**
 * Static `require`s, because Metro resolves them at build time and cannot resolve a
 * computed path. This map is also the complete list of cues — if it is not here it cannot
 * be played, which is the point.
 */
const SOURCES = {
  match: require('../../assets/sounds/match.wav'),
  purchase: require('../../assets/sounds/purchase.wav'),
  reward: require('../../assets/sounds/reward.wav'),
  message: require('../../assets/sounds/message.wav'),
} as const;

type Cue = keyof typeof SOURCES;

/**
 * Players are built on first play and kept, not built per call.
 *
 * A player holds a decoded buffer and a native handle. Creating one per play would mean a
 * decode on the UI thread at exactly the moment something is animating, and — because
 * `createAudioPlayer` explicitly does *not* release automatically — a leaked native object
 * every time. Four live players for the life of the process is the cheap end of the trade.
 */
const players = new Map<Cue, AudioPlayer>();

let configured = false;

function configure(): void {
  if (configured) return;
  configured = true;

  void setAudioModeAsync({
    playsInSilentMode: false,
    interruptionMode: 'mixWithOthers',
    shouldPlayInBackground: false,
  }).catch(() => {});
}

function play(cue: Cue): void {
  if (!useSoundEnabled.getState().enabled) return;

  try {
    configure();

    let player = players.get(cue);
    if (!player) {
      player = createAudioPlayer(SOURCES[cue]);
      players.set(cue, player);
    }

    // Rewind first, so a cue fired twice in quick succession restarts rather than being
    // ignored because it is already at the end of itself. Wrapped in `Promise.resolve` so
    // this works whether or not `seekTo` returns a promise on a given platform.
    const target = player;
    void Promise.resolve(target.seekTo(0))
      .then(() => target.play())
      .catch(() => {});
  } catch {
    // Same contract as `haptics.ts`: no audio route, no native module in an older
    // development build, or an OS that declines. None of these are worth a console warning
    // that trains people to ignore the console, and none should ever break a call site.
  }
}

/** A mutual match. The longest cue, and the only one that gets four notes. */
export function match(): void {
  play('match');
}

/** Something was bought — coins spent on a frame, a consumable, a membership. */
export function purchase(): void {
  play('purchase');
}

/** Coins or a badge arrived. The earning side, distinct from the spending side. */
export function reward(): void {
  play('reward');
}

/** Something came in: a message, a friend request, community activity. */
export function message(): void {
  play('message');
}
